### ISSUE TITLE
真机测试出现 Access denied finding property "net.dns1"，且插件一直不能加载完成

### ISSUE THREAD

**Issue by FWorldCodeZ** [aliyoge/flutter_file_preview#4]
手机是魅族16th
Android版本：8.1.0
```
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 24}
```
在控制台中出现：
```
W/System.err(16656): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.BaseBundle.getString(java.lang.String)' on a null object reference
W/System.err(16656): 	at android.content.res.flymetheme.FlymeThemeHelper.getMetaDataFromApp(FlymeThemeHelper.java:1031)
W/System.err(16656): 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:712)
W/System.err(16656): 	at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
W/System.err(16656): 	at android.content.res.Resources.getDrawable(Resources.java:830)
W/System.err(16656): 	at android.content.res.Resources.getDrawable(Resources.java:805)
W/System.err(16656): 	at android.app.ApplicationPackageManager$Injector.getDefaultFlymeActivityIcon(ApplicationPackageManager.java:2912)
W/System.err(16656): 	at android.app.ApplicationPackageManager.getDefaultActivityIcon(ApplicationPackageManager.java:1282)
W/System.err(16656): 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2722)
W/System.err(16656): 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:423)
W/System.err(16656): 	at android.app.Activity.setContentView(Activity.java:2715)
W/System.err(16656): 	at zzaning.com.filepreview.FileDisplayActivity.onCreate(FileDisplayActivity.java:36)
W/System.err(16656): 	at android.app.Activity.performCreate(Activity.java:7066)
W/System.err(16656): 	at android.app.Activity.performCreate(Activity.java:7057)
W/System.err(16656): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1216)
W/System.err(16656): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
W/System.err(16656): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061)
W/System.err(16656): 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
W/System.err(16656): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747)
W/System.err(16656): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(16656): 	at android.os.Looper.loop(Looper.java:192)
W/System.err(16656): 	at android.app.ActivityThread.main(ActivityThread.java:6840)
W/System.err(16656): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(16656): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
W/System.err(16656): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
I/MobclickAgent(16656): Extend current session: 496EEC59E0BD8D8297550EF94990A265
W/System.err(16656): android.content.pm.PackageManager$NameNotFoundException: com.tencent.mtt
W/System.err(16656): 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:193)
W/System.err(16656): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:149)
W/System.err(16656): 	at com.tencent.common.utils.MttLoader.getBrowserInfo(TbsJavaCore:442)
W/System.err(16656): 	at com.tencent.mtt.external.reader.MttFileReaderWrapper.<init>(TbsJavaCore:151)
W/System.err(16656): 	at com.tencent.tbs.tbsshell.partner.reader.c.a(TbsJavaCore:418)
W/System.err(16656): 	at com.tencent.tbs.tbsshell.partner.reader.c.a(TbsJavaCore:129)
W/System.err(16656): 	at com.tencent.tbs.reader.TbsReader.openFile(TbsJavaCore:59)
W/System.err(16656): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(16656): 	at com.tencent.smtt.export.external.DexLoader.invokeMethod(Unknown Source:14)
W/System.err(16656): 	at com.tencent.smtt.sdk.ReaderWizard.openFile(Unknown Source:44)
W/System.err(16656): 	at com.tencent.smtt.sdk.TbsReaderView.openFile(Unknown Source:61)
W/System.err(16656): 	at zzaning.com.filepreview.SuperFileView2.displayFile(SuperFileView2.java:80)
W/System.err(16656): 	at zzaning.com.filepreview.FileDisplayActivity$2.onResponse(FileDisplayActivity.java:155)
W/System.err(16656): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
W/System.err(16656): 	at android.os.Handler.handleCallback(Handler.java:790)
W/System.err(16656): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(16656): 	at android.os.Looper.loop(Looper.java:192)
W/System.err(16656): 	at android.app.ActivityThread.main(ActivityThread.java:6840)
W/System.err(16656): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(16656): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
W/System.err(16656): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
E/superFileLog(16656): ****************************************************5045
I/zygote64(16656): Do partial code cache collection, code=493KB, data=318KB
I/zygote64(16656): After code cache collection, code=493KB, data=318KB
I/zygote64(16656): Increasing code cache capacity to 2MB
W/down-pool-3(16656): type=1400 audit(0.0:36673438): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=15543 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0
E/libc    (16656): Access denied finding property "net.dns1"
I/qtaguid (16656): Untagging socket 139 failed errno=-22
E/QB_DOWN::DownloadWorker(16656): ERR [run]
E/QB_DOWN::DownloadWorker(16656): java.net.SocketTimeoutException: timeout
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:756)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:163)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:223)
E/QB_DOWN::DownloadWorker(16656): 	at com.tencent.common.http.HttpRequesterBase.parseResponseHeaders(TbsJavaCore:728)
E/QB_DOWN::DownloadWorker(16656): 	at com.tencent.common.http.HttpRequesterBase.a(TbsJavaCore:198)
E/QB_DOWN::DownloadWorker(16656): 	at com.tencent.common.http.HttpRequesterBase.a(TbsJavaCore:187)
E/QB_DOWN::DownloadWorker(16656): 	at com.tencent.common.http.HttpRequesterBase.execute(TbsJavaCore:81)
E/QB_DOWN::DownloadWorker(16656): 	at com.tencent.mtt.browser.download.engine.network.DownloadConnection.execute(TbsJavaCore:173)
E/QB_DOWN::DownloadWorker(16656): 	at com.tencent.mtt.browser.download.engine.core.DownloadWorker.run(TbsJavaCore:254)
E/QB_DOWN::DownloadWorker(16656): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/QB_DOWN::DownloadWorker(16656): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/QB_DOWN::DownloadWorker(16656): 	at com.tencent.mtt.browser.download.engine.core.DownloadThreadPolicy$2.run(TbsJavaCore:51)
E/QB_DOWN::DownloadWorker(16656): Caused by: java.net.SocketException: Socket closed
E/QB_DOWN::DownloadWorker(16656): 	at java.net.SocketInputStream.read(SocketInputStream.java:203)
E/QB_DOWN::DownloadWorker(16656): 	at java.net.SocketInputStream.read(SocketInputStream.java:139)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
E/QB_DOWN::DownloadWorker(16656): 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
E/QB_DOWN::DownloadWorker(16656): 	... 20 more
```

**Comment by aliyoge** [comment]
@FWorldCodeZ 请看一下新版本。
